implementation of the class for the serialization
Compile right, but doesn't work properly in somes cases (as with the
last code). In fact we need to find what to do when bitcoin return an
error instead of a result. I couldn't test it entirely since of the bug.
Frightening result:
C:\Program Files (x86)\Bitcoin\daemon>bitcoind.exe getrawtransaction
53a42ddeb6f
c22106bee6432b09b86ad6765a5d928b2ee70a8ca759fa7cf0676
error: {"code":-5,"message":"No information available about
transaction"}

So with this transaction, our code doesn't work. How is this possible
bitcoin doesn't have the information about this transaction (at least
for me)?